### ISSUE TITLE
Laser bolt spawns at player feet

### ISSUE THREAD

**Issue by roryclaasen** [GOGO98901/RorysMod#17]
Laser bolt spawns at player feet

**Comment by roryclaasen** [comment]
Note that the laser now spawns in the centre of the player and so I may offset it at a later date

**Comment by ghost** [comment]
Would it be a good idea to fire it from eye level, I'm not sure how difficult that would be but it would cause projectiles to go through the cross hairs... (if that doesn't happen already)

**Comment by roryclaasen** [comment]
The projectile travels to the cross hair no mater where it is spawned. I believe in 1.6.4 (not sure about 1.7.10) the ic2 mining laser spawned it from the rifle and so I may move the spawn point over to the right arm

**Comment by roryclaasen** [comment]
This is that part that sets the new position so it wouldn't be that hard to move it again
https://github.com/GOGO98901/RorysMod/blob/master/src/main/java/net/roryclaasen/rorysmod/entity/EntityLaser.java#L25

**Comment by ghost** [comment]
Yeah, if you do that I think it'll look pretty good... although firing lasers from your chest also sounds fun...
