### ISSUE TITLE
MODULARLAZARS

### ISSUE THREAD

**Issue by ghost** [GOGO98901/RorysMod#2]

**Comment by roryclaasen** [comment]
Sorry but I will need more details than that

**Comment by roryclaasen** [comment]
@youngsmilodon said "I apologize for being an inconvenience but the mod you made 'modular lasers' doesn't seem to be working, could you fix this please?"

**Comment by roryclaasen** [comment]
Update see #17

**Comment by roryclaasen** [comment]
This has now been fully implemented
